version: 2
jobs:
  build_and_test:
    working_directory: ~/app
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Run Tests
          command: npm test
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build_and_test
      - deploy_staging:
          filters:
            branches:
              only: master
          requires:
            - build_and_test
          command: sh ./circleci/deploy.sh "${CIRCLE_BRANCH}"
      - deploy_prod:
          filters:
            tags:
              only: /^v.*/
          requires:
            - build_and_test
          command: sh ./circleci/deploy.sh "${CIRCLE_TAG}"
