version: 2
jobs:
  build_and_test:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Run Tests
          command: npm test
  trigger_quay:
    docker:
      - image: alpine/git
    steps:
      - checkout
      - run:
          name: Install curl
          command: |
            apk update && apk add curl curl-dev
      - run:
          name: Trigger Quay Build
          command: sh .circleci/trigger_quay.sh

workflows:
  version: 2
  build_test_trigger:
    jobs:
      - build_and_test
      - trigger_quay:
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/
          requires:
            - build_and_test
