version: 2
jobs:
  build_and_test:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Run Tests
          command: npm test
  deploy_staging:
    docker:
      - image: alpine/git
    steps:
      - checkout
      - run:
          name: Deploy to staging
          command: sh ./circleci/deploy.sh "${CIRCLE_BRANCH}"
  deploy_prod:
    docker:
      - image: alpine/git
    steps:
      - checkout
      - run:
          name: Deploy to production
          command: sh ./circleci/deploy.sh "${CIRCLE_TAG}"

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build_and_test
      - deploy_staging:
          filters:
            branches:
              only: master
          requires:
            - build_and_test
      - deploy_prod:
          filters:
            tags:
              only: /^v.*/
          requires:
            - build_and_test
